
/**
 * Prefix map for different test actions.
 */
const TestGetActions = {
    TEST_HEALTHCHECK: "TEST_HEALTHCHECK",
    TEST_HEALTHCHECK_V1: "TEST_HEALTHCHECK_V1",
    TEST_EMAIL_SENDING: "TEST_EMAIL_SENDING",
    TEST_EMAIL_SENDING_QUOTE_EMAIL: "TEST_EMAIL_SENDING_QUOTE_EMAIL",
    TEST_EMAIL_QUOTESENDING_WITHFORWARDING: "TEST_EMAIL_QUOTESENDING_WITHFORWARDING"
  };
  